// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VetSystem.Infrastructure.Persistence;

#nullable disable

namespace VetSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523112141_M5_VisitsAndMedical")]
    partial class M5_VisitsAndMedical
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VetSystem.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DocDate")
                        .HasColumnType("date")
                        .HasColumnName("doc_date");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("file_type");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UploadStatus")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("upload_status");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("ix_attachments_visit");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_attachments_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_attachments_environment_id_updated_at");

                    b.ToTable("attachments", null, t =>
                        {
                            t.HasCheckConstraint("ck_attachments_file_type", "file_type IN ('photo','pdf')");

                            t.HasCheckConstraint("ck_attachments_upload_status", "upload_status IN ('pending','uploaded','failed')");
                        });
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<Guid?>("AssignedDoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_doctor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("full_name");

                    b.Property<string>("IdNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id_number");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PhonePrimary")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_primary");

                    b.Property<string>("PhoneSecondary")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_secondary");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("AssignedDoctorId")
                        .HasDatabaseName("ix_customers_assigned_doctor_id");

                    b.HasIndex("EnvironmentId", "AssignedDoctorId")
                        .HasDatabaseName("ix_customers_assigned_doctor");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_customers_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "PhonePrimary")
                        .IsUnique()
                        .HasDatabaseName("ux_customers_env_phone")
                        .HasFilter("phone_primary IS NOT NULL");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_customers_environment_id_updated_at");

                    b.ToTable("customers", null, t =>
                        {
                            t.HasCheckConstraint("ck_customers_type", "type IN ('regular_farm','home','cattle_farm','poultry_farm')");
                        });
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.DailyFollowUp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdministeredMeds")
                        .HasColumnType("text")
                        .HasColumnName("administered_meds");

                    b.Property<string>("Condition")
                        .HasColumnType("text")
                        .HasColumnName("condition");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("heart_rate");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("RespiratoryRate")
                        .HasColumnType("integer")
                        .HasColumnName("respiratory_rate");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_daily_follow_ups");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_daily_follow_ups_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_daily_follow_ups_environment_id_updated_at");

                    b.HasIndex("VisitId", "EntryDate")
                        .HasDatabaseName("ix_followups_visit");

                    b.ToTable("daily_follow_ups", (string)null);
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_environments");

                    b.ToTable("environments", null, t =>
                        {
                            t.HasCheckConstraint("ck_environments_mode", "mode IN ('solo','partnership')");
                        });
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.FieldInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_field_inventories");

                    b.HasIndex("DoctorId")
                        .IsUnique()
                        .HasDatabaseName("ux_field_inventories_doctor");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_field_inventories_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_field_inventories_environment_id_updated_at");

                    b.ToTable("field_inventories", (string)null);
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.IdempotencyKey", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<Guid?>("ResultRef")
                        .HasColumnType("uuid")
                        .HasColumnName("result_ref");

                    b.HasKey("Key")
                        .HasName("pk_idempotency_keys");

                    b.HasIndex("EnvironmentId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_idempotency_keys_env_key");

                    b.ToTable("idempotency_keys", (string)null);
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<Guid?>("FromLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_location_id");

                    b.Property<string>("FromLocationType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("from_location_type");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("movement_type");

                    b.Property<Guid>("PerformedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("QuantityDelta")
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("quantity_delta");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ToLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_location_id");

                    b.Property<string>("ToLocationType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("to_location_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_inventory_movements");

                    b.HasIndex("PerformedBy")
                        .HasDatabaseName("ix_inventory_movements_performed_by");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_inventory_movements_product_id");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("ix_inventory_movements_visit_id");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_inventory_movements_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_movements_env_idempotency");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_inventory_movements_environment_id_updated_at");

                    b.HasIndex("EnvironmentId", "ProductId", "CreatedAt")
                        .HasDatabaseName("ix_inv_moves_product_time");

                    b.ToTable("inventory_movements", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_movements_from_location_type", "from_location_type IS NULL OR from_location_type IN ('warehouse','field')");

                            t.HasCheckConstraint("ck_inventory_movements_to_location_type", "to_location_type IS NULL OR to_location_type IN ('warehouse','field')");

                            t.HasCheckConstraint("ck_inventory_movements_type", "movement_type IN ('receive','adjust','load_to_field','unload_from_field','sale_deduct','return_add')");
                        });
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Ledger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("balance");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_ledgers");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ux_ledgers_customer");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_ledgers_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_ledgers_environment_id_updated_at");

                    b.ToTable("ledgers", null, t =>
                        {
                            t.HasCheckConstraint("ck_ledgers_status", "status IN ('open','has_debt','closed')");
                        });
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("balance_after");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entry_type");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_id");

                    b.Property<Guid?>("ReceiptVoucherId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_voucher_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_ledger_entries");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_ledger_entries_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_entries_env_idempotency");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_ledger_entries_environment_id_updated_at");

                    b.HasIndex("LedgerId", "CreatedAt")
                        .HasDatabaseName("ix_ledger_entries_ledger");

                    b.ToTable("ledger_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_ledger_entries_type", "entry_type IN ('invoice','service_fee','exam_fee','receipt_voucher','adjustment')");
                        });
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_permissions_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_permissions_env_key");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_permissions_environment_id_updated_at");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Breed")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("breed");

                    b.Property<string>("ColorMarks")
                        .HasColumnType("text")
                        .HasColumnName("color_marks");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("HealthNotes")
                        .HasColumnType("text")
                        .HasColumnName("health_notes");

                    b.Property<string>("MicrochipNo")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("microchip_no");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("Sex")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("sex");

                    b.Property<string>("Species")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("species");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("WeightLatest")
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("weight_latest");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_pets");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_pets_customer_id");

                    b.HasIndex("EnvironmentId", "CustomerId")
                        .HasDatabaseName("ix_pets_customer");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_pets_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_pets_environment_id_updated_at");

                    b.ToTable("pets", null, t =>
                        {
                            t.HasCheckConstraint("ck_pets_sex", "sex IS NULL OR sex IN ('male','female','unknown')");
                        });
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DispenseType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("dispense_type");

                    b.Property<string>("Dosage")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("dosage");

                    b.Property<string>("Duration")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("duration");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("Frequency")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("frequency");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_prescriptions");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_prescriptions_product_id");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("ix_prescriptions_visit");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_prescriptions_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_prescriptions_environment_id_updated_at");

                    b.ToTable("prescriptions", null, t =>
                        {
                            t.HasCheckConstraint("ck_prescriptions_dispense_type", "dispense_type IN ('administered_in_clinic','dispensed_to_owner')");
                        });
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Procedure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("price");

                    b.Property<string>("ResultFileUrl")
                        .HasColumnType("text")
                        .HasColumnName("result_file_url");

                    b.Property<string>("ResultText")
                        .HasColumnType("text")
                        .HasColumnName("result_text");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_procedures");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_procedures_service_id");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("ix_procedures_visit");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_procedures_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_procedures_environment_id_updated_at");

                    b.ToTable("procedures", (string)null);
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("barcode");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameLatin")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_latin");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("purchase_price");

                    b.Property<decimal>("ReorderPoint")
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("reorder_point");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("selling_price");

                    b.Property<string>("Supplier")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("supplier");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit_of_measure");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("EnvironmentId", "Barcode")
                        .IsUnique()
                        .HasDatabaseName("ux_products_env_barcode")
                        .HasFilter("barcode IS NOT NULL");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_products_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_products_environment_id_updated_at");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_category", "category IN ('medication','product')");
                        });
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ReplacedById")
                        .HasDatabaseName("ix_refresh_tokens_replaced_by_id");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_refresh_tokens_hash");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_refresh_tokens_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_refresh_tokens_environment_id_updated_at");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_user_expires");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.RegistrationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("RequestedRoleKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("requested_role_key");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("text")
                        .HasColumnName("review_notes");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_registration_requests");

                    b.HasIndex("ReviewedBy")
                        .HasDatabaseName("ix_registration_requests_reviewed_by");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_registration_requests_user_id");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_registration_requests_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "Status")
                        .HasDatabaseName("ix_registration_requests_env_status");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_registration_requests_environment_id_updated_at");

                    b.ToTable("registration_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_registration_requests_status", "status IN ('pending','approved','rejected')");
                        });
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_roles_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_env_key");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_roles_environment_id_updated_at");

                    b.ToTable("roles", null, t =>
                        {
                            t.HasCheckConstraint("ck_roles_key", "key IN ('admin','accountant','vet_clinic','vet_field','vet_both','receptionist','cashier','inventory_staff')");
                        });
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DefaultPrice")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("default_price");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameLatin")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_latin");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_services_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_services_environment_id_updated_at");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.StockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("location_type");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_stock_items");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_stock_items_product_id");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_stock_items_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "ProductId")
                        .HasDatabaseName("ix_stock_items_product");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_stock_items_environment_id_updated_at");

                    b.HasIndex("LocationType", "LocationId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ux_stock_items_location_product");

                    b.ToTable("stock_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_items_location_type", "location_type IN ('warehouse','field')");
                        });
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.SyncTestRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_sync_test_records");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_sync_test_records_env_deleted");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_sync_test_records_env_updated");

                    b.ToTable("sync_test_records", (string)null);
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.SystemSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DefaultExamFee")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("default_exam_fee");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("EntitlementEnabledGlobal")
                        .HasColumnType("boolean")
                        .HasColumnName("entitlement_enabled_global");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<int>("ExpirationWarningDays")
                        .HasColumnType("integer")
                        .HasColumnName("expiration_warning_days");

                    b.Property<string>("Extra")
                        .HasColumnType("jsonb")
                        .HasColumnName("extra");

                    b.Property<string>("InvoiceTaxDetails")
                        .HasColumnType("jsonb")
                        .HasColumnName("invoice_tax_details");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<decimal>("LowStockThresholdPct")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("low_stock_threshold_pct");

                    b.Property<bool>("TaxEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("tax_enabled");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tax_rate");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_system_settings");

                    b.HasIndex("EnvironmentId")
                        .IsUnique()
                        .HasDatabaseName("ux_system_settings_env");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_system_settings_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_system_settings_environment_id_updated_at");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("full_name");

                    b.Property<string>("LicenseDetails")
                        .HasColumnType("jsonb")
                        .HasColumnName("license_details");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("license_number");

                    b.Property<string>("NumberPrefix")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("number_prefix");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhonePrimary")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_primary");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_users_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "NumberPrefix")
                        .IsUnique()
                        .HasDatabaseName("ux_users_env_number_prefix")
                        .HasFilter("number_prefix IS NOT NULL");

                    b.HasIndex("EnvironmentId", "PhonePrimary")
                        .IsUnique()
                        .HasDatabaseName("ux_users_env_phone");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_users_environment_id_updated_at");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_status", "status IN ('inactive','active','suspended')");
                        });
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.UserPermissionOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("effect");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_user_permission_overrides");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_user_permission_overrides_permission_id");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_user_permission_overrides_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_user_permission_overrides_environment_id_updated_at");

                    b.HasIndex("UserId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_permission_overrides_user_perm");

                    b.ToTable("user_permission_overrides", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_permission_overrides_effect", "effect IN ('grant','deny')");
                        });
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Vaccination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CertificateUrl")
                        .HasColumnType("text")
                        .HasColumnName("certificate_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("DateGiven")
                        .HasColumnType("date")
                        .HasColumnName("date_given");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<DateOnly?>("NextDueDate")
                        .HasColumnType("date")
                        .HasColumnName("next_due_date");

                    b.Property<Guid?>("PetId")
                        .HasColumnType("uuid")
                        .HasColumnName("pet_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VaccineType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("vaccine_type");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_vaccinations");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_vaccinations_customer_id");

                    b.HasIndex("PetId")
                        .HasDatabaseName("ix_vaccinations_pet_id");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("ix_vaccinations_visit_id");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_vaccinations_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "NextDueDate")
                        .HasDatabaseName("ix_vaccinations_due")
                        .HasFilter("next_due_date IS NOT NULL");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_vaccinations_environment_id_updated_at");

                    b.ToTable("vaccinations", (string)null);
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("ChiefComplaint")
                        .HasColumnType("text")
                        .HasColumnName("chief_complaint");

                    b.Property<string>("ClinicalNotes")
                        .HasColumnType("text")
                        .HasColumnName("clinical_notes");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<decimal?>("ExamFeeApplied")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("exam_fee_applied");

                    b.Property<string>("FinalDiagnosis")
                        .HasColumnType("text")
                        .HasColumnName("final_diagnosis");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("heart_rate");

                    b.Property<string>("IcdVetCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("icd_vet_code");

                    b.Property<Guid?>("PetId")
                        .HasColumnType("uuid")
                        .HasColumnName("pet_id");

                    b.Property<string>("PreliminaryDiagnosis")
                        .HasColumnType("text")
                        .HasColumnName("preliminary_diagnosis");

                    b.Property<Guid?>("ReceptionistId")
                        .HasColumnType("uuid")
                        .HasColumnName("receptionist_id");

                    b.Property<int?>("RespiratoryRate")
                        .HasColumnType("integer")
                        .HasColumnName("respiratory_rate");

                    b.Property<string>("Severity")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Symptoms")
                        .HasColumnType("text")
                        .HasColumnName("symptoms");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VisitNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("visit_number");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("visit_type");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("weight");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_visits");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_visits_customer_id");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("ix_visits_doctor_id");

                    b.HasIndex("PetId")
                        .HasDatabaseName("ix_visits_pet_id");

                    b.HasIndex("ReceptionistId")
                        .HasDatabaseName("ix_visits_receptionist_id");

                    b.HasIndex("EnvironmentId", "BatchId")
                        .HasDatabaseName("ix_visits_batch");

                    b.HasIndex("EnvironmentId", "ContractId")
                        .HasDatabaseName("ix_visits_contract");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_visits_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_visits_environment_id_updated_at");

                    b.HasIndex("EnvironmentId", "VisitNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_visits_env_number");

                    b.HasIndex("EnvironmentId", "CustomerId", "StartedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_visits_customer_time");

                    b.HasIndex("EnvironmentId", "DoctorId", "StartedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_visits_doctor_time");

                    b.ToTable("visits", null, t =>
                        {
                            t.HasCheckConstraint("ck_visits_severity", "severity IS NULL OR severity IN ('mild','moderate','severe','critical')");

                            t.HasCheckConstraint("ck_visits_status", "status IN ('open','in_progress','completed','cancelled')");

                            t.HasCheckConstraint("ck_visits_type", "visit_type IN ('in_clinic','field')");
                        });
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_warehouses");

                    b.HasIndex("EnvironmentId", "DeletedAt")
                        .HasDatabaseName("ix_warehouses_environment_id_deleted_at");

                    b.HasIndex("EnvironmentId", "UpdatedAt")
                        .HasDatabaseName("ix_warehouses_environment_id_updated_at");

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("VetSystem.Domain.Entities.Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_visits_visit_id");
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Customer", b =>
                {
                    b.HasOne("VetSystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedDoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_customers_users_assigned_doctor_id");
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.DailyFollowUp", b =>
                {
                    b.HasOne("VetSystem.Domain.Entities.Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_follow_ups_visits_visit_id");
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.FieldInventory", b =>
                {
                    b.HasOne("VetSystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_field_inventories_users_doctor_id");
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.InventoryMovement", b =>
                {
                    b.HasOne("VetSystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_movements_users_performed_by");

                    b.HasOne("VetSystem.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_movements_products_product_id");

                    b.HasOne("VetSystem.Domain.Entities.Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_movements_visits_visit_id");
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Ledger", b =>
                {
                    b.HasOne("VetSystem.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledgers_customers_customer_id");
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.LedgerEntry", b =>
                {
                    b.HasOne("VetSystem.Domain.Entities.Ledger", null)
                        .WithMany()
                        .HasForeignKey("LedgerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_entries_ledgers_ledger_id");
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Pet", b =>
                {
                    b.HasOne("VetSystem.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pets_customers_customer_id");
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("VetSystem.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_prescriptions_products_product_id");

                    b.HasOne("VetSystem.Domain.Entities.Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_prescriptions_visits_visit_id");
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Procedure", b =>
                {
                    b.HasOne("VetSystem.Domain.Entities.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_procedures_services_service_id");

                    b.HasOne("VetSystem.Domain.Entities.Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_procedures_visits_visit_id");
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("VetSystem.Domain.Entities.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_replaced_by_id");

                    b.HasOne("VetSystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.RegistrationRequest", b =>
                {
                    b.HasOne("VetSystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_registration_requests_users_reviewed_by");

                    b.HasOne("VetSystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registration_requests_users_user_id");
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("VetSystem.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("VetSystem.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.StockItem", b =>
                {
                    b.HasOne("VetSystem.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_items_products_product_id");
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.User", b =>
                {
                    b.HasOne("VetSystem.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.UserPermissionOverride", b =>
                {
                    b.HasOne("VetSystem.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permission_overrides_permissions_permission_id");

                    b.HasOne("VetSystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permission_overrides_users_user_id");
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Vaccination", b =>
                {
                    b.HasOne("VetSystem.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_vaccinations_customers_customer_id");

                    b.HasOne("VetSystem.Domain.Entities.Pet", null)
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_vaccinations_pets_pet_id");

                    b.HasOne("VetSystem.Domain.Entities.Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_vaccinations_visits_visit_id");
                });

            modelBuilder.Entity("VetSystem.Domain.Entities.Visit", b =>
                {
                    b.HasOne("VetSystem.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_visits_customers_customer_id");

                    b.HasOne("VetSystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_visits_users_doctor_id");

                    b.HasOne("VetSystem.Domain.Entities.Pet", null)
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_visits_pets_pet_id");

                    b.HasOne("VetSystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReceptionistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_visits_users_receptionist_id");
                });
#pragma warning restore 612, 618
        }
    }
}
